### ISSUE TITLE
doesn't work (yet) on atom 1.19

### ISSUE THREAD

**Issue by cxn-astracz** [erikjansson/atom-tab-title#5]
[Enter steps to reproduce:]

1. upgrade to atom 1.19

**Atom**: 1.19.0-beta5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [tab-title](https://github.com/erikjansson/atom-tab-title) package 0.3.4

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At ~/.atom/packages/tab-title/lib/tab-title.js:78

TypeError: Cannot read property '0' of undefined
    at Object.generateTitle (/packages/tab-title/lib/tab-title.js:78:33)
    at items.forEach (/packages/tab-title/lib/tab-title.js:89:30)
    at Array.forEach (native)
    at Object.setTitle (/packages/tab-title/lib/tab-title.js:85:15)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:635:38
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.reset (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:87:26)
    at TextEditor.module.exports.TextEditor.update (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:531:31)
    at TextEditor.module.exports.TextEditor.setEditorWidthInChars (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:896:25)
    at TextEditorComponent.updateModelSoftWrapColumn (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2020:30)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:348:16)
    at TextEditorComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:259:16)
    at TextEditorComponent.didShow (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1415:18)
    at TextEditorComponent.didAttach (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1385:20)
    at HTMLElement.attachedCallback (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-element.js:41:25)
    at HTMLElement.module.exports.PaneContainerElement.rootChanged (/Applications/Atom Beta.app/Contents/Resources/app/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.setRoot (/Applications/Atom Beta.app/Contents/Resources/app/src/pane-container.js:138:24)
    at PaneContainer.deserialize (/Applications/Atom Beta.app/Contents/Resources/app/src/pane-container.js:58:16)
    at WorkspaceCenter.deserialize (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace-center.js:31:30)
    at Workspace.deserialize (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:416:42)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:1263:35
```

### Commands

```
     -0:06.8.0 project-manager:list-projects (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-python-run 0.7.3 
busy-signal 1.4.3 
git-time-machine 1.5.9 
intentions 1.1.5 
language-docker 1.1.8 
less-than-slash 0.17.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.3 
minimap 4.29.3 
pretty-json 1.6.4 
project-manager 3.3.5 
restore-windows 0.4.1 
Stylus 3.1.1 
sublime-web-syntax 0.0.2 
tab-title 0.3.4 
tablr 1.8.3 
```

**Comment by kimroen** [comment]
This seems to be because in Atom `1.19`, the `TextBuffer` class has been entirely rewritten, and does not provide lines of text like we're accessing them here. Here's the PR where this was changed in Atom: https://github.com/atom/atom/pull/14435

> Instead of storing the text as a mutable array of lines, we store it as flat immutable string representing the file's original content, plus a Patch representing the user's unsaved changes. This is somewhat similar to the piece table data structure used in some other editors.

This means that all the uses of `buffer` on a `pane` in the code should probably be looked over and checked to make sure the interface is still valid. Hopefully there's something we can use that is backwards compatible.

In the particular case, the `lines` function is not available for the buffer here: 

https://github.com/erikjansson/atom-tab-title/blob/ecd27c8badfc4363ccb2ad7b8cdcfb7fec45745f/lib/tab-title.js#L77-L80

In the new version of `TextBuffer`, you can call `getText` with a `startRow` and `endRow` to get a particular range of lines:

https://github.com/atom/text-buffer/blob/bb9134fc93713273dcccafd9e917e00f1f2f58cc/src/display-layer.js#L585-L587

It could be that this API is available for earlier versions of Atom as well (at least 1.18), I've seen some issues on other packages that could use `getLineCount` instead of `lines.length` and have that work on both versions.

Hope that helps!

**Comment by erikjansson** [comment]
Thank you friends! Looking into this.

**Comment by andresrinivasan** [comment]
@erikjansson, please see my pull request for a resolution to this as well as #7 and #8.

**Comment by erikjansson** [comment]
Fixed in #9. Package update incoming!

**Comment by maxbrunsfeld** [comment]
~~FWIW, The buffer also has a public `lineForRow` method.~~

Edit - nevermind! It looks like that's what you used.

**Comment by erikjansson** [comment]
Thanks though, @maxbrunsfeld!
